Widescreen implementation based on Crispy Doom
fabiangreffrath/woof pull request #107
Opened 2021-01-23 08:32 UTC by rfomin

This is incomplete, but it mostly works:

![scrn1](https://user-images.githubusercontent.com/5077629/105573366-97989d80-5d8f-11eb-985f-109ef2e0dbe8.png)

What do you think? Should I continue?

Related issue: #94

2021-01-23 10:52 UTC, fabiangreffrath commented
Impressive, thank you very much! In how far is this incomplete? Yes, of course you should continue. 😉

2021-01-23 11:01 UTC, rfomin commented
> In how far is this incomplete?

It needs the support of wide assets. I haven't tested bunny scroll end ending screens, nothing major.

2021-01-23 11:16 UTC, fabiangreffrath commented
I see. Would you like me to review this, so we can get it merged first and add wide asset support afterwards?

2021-01-23 11:20 UTC, rfomin commented
Not now, I need to fix few things. I will tell you when I'm ready for review.

2021-01-23 11:45 UTC, fabiangreffrath commented
Looking forward to it, please keep up the good work. 👍

2021-01-23 21:51 UTC, rfomin commented
Ready to review.

2021-01-25 02:18 UTC, rfomin commented
Will you include wide assets in Woof distribution? I propose this file structure:
```
wideassets/
├── wide_d1.wad
├── wide_d2.wad
├── wide_tnt.wad
└── wide_pl.wad
```

2021-01-25 05:41 UTC, fabiangreffrath commented
> Will you include wide assets in Woof distribution? I propose this file structure:
> 
> ```
> wideassets/
> ├── wide_d1.wad
> ├── wide_d2.wad
> ├── wide_tnt.wad
> └── wide_pl.wad
> ```

Absolutely no. The assets are copyrighted by id software and they didn't grant me any license to distribute them.

2021-01-25 05:43 UTC, rfomin commented
https://bethesda.net/en/game/doom-widescreen-mods
Also, GZDoom did it.

2021-01-25 08:05 UTC, fabiangreffrath commented
I didn't even know this, thank you! Anyway, this is a free software project, licensed under the GPL. And I have taken measures to make sure that everything in this project complies to this license, e.g. by removing some of the embedded lumps that resembled parts of Doom's original artwork or by replacing the embedded dog sprites and sounds from Wolf-3D and the plasma ball sprites from the Doom Beta by strictly free alternatives. Now I am not going to dilute this achievement by adding non-free [1] data files that everybody could download himself anyway. I hope you understand.

[1] https://wiki.debian.org/FreeSoftware

2021-01-25 08:21 UTC, rfomin commented
Okay, then I consider this complete. Except for multi-monitor support, because now we need screen sizes.

2021-01-25 11:49 UTC, fabiangreffrath requested changes
Very good, mostly style issues left.

2021-01-25 11:49 UTC, fabiangreffrath commented on Source/i_video.c
> +      SCREENWIDTH = (SCREENWIDTH + 3) & (int)~3;
I have recently changed this to `SCREENWIDTH = (SCREENWIDTH + (crispy->hires ? 0 : 3)) & (int)~3;` in Crispy, please do the same here.

2021-01-25 11:49 UTC, fabiangreffrath commented on Source/f_finale.c
> +
One blank line too much. ;)

2021-01-25 11:49 UTC, fabiangreffrath commented on Source/m_menu.c
> +          byte  dot = src[(((y>>1)&63)<<6) + ((x>>1)&63)];
`const byte` and one less space char, please.

2021-01-25 11:49 UTC, fabiangreffrath commented on Source/m_menu.c
> + //      for (y = 0 ; y < SCREENHEIGHT ; src = ((++y & 63)<<6) + back_src,
Please comment out entire code ranges by using `/* ... */`, applies below as well.

2021-01-25 11:49 UTC, fabiangreffrath commented on Source/r_draw.c
> +int  linesize;// = SCREENWIDTH;  // killough 11/98
Let's please still initialize this with `ORIGWIDTH` here.

2021-01-25 11:49 UTC, fabiangreffrath commented on Source/r_main.c
> +
Excess blank line.

2021-01-25 11:49 UTC, fabiangreffrath commented on Source/st_stuff.c
> +          for (int y = (SCREENHEIGHT-ST_HEIGHT)<<1; y < SCREENHEIGHT<<1; y++)
`x` and `y` are already declared above.

2021-01-25 12:52 UTC, merged

2021-01-25 12:52 UTC, fabiangreffrath commented
Thank you very much! Wow, this is really exciting...