Invoke ST_doPaletteStuff every game tic, not every frame
fabiangreffrath/woof pull request #1316
Opened 2023-12-10 07:58 UTC by JNechaevsky

AFAIR, we was discussing it with @fabiangreffrath ages ago, but somehow it didn't get into Crispy Doom and Woof.

The idea is simple: back in a day when there was no uncapped mode, both `ST_Drawer` and `ST_Ticker` were updating on same speed. Nowadays, in uncapped mode `ST_Drawer` is updating every frame, while `ST_Ticker` is still updating every game tic. But in uncapped framerate there is no need to check for palette changes every frame, since such changes are still related to game tics and game is not actually "faster".

So, this must be a micro-optimization, for getting rid of some unnecessary often checks. 

P.S. Is it okay to have extern declaration in .h file? `ST_doPaletteStuff` is not needed globally, but making prototypes in the middle of .c files feels yucky.

2023-12-10 11:06 UTC, fabiangreffrath requested changes
Thank you! I'd prefer if you could make that function static and add a forward-declaration in the c-file right before the function where it's actually called.

2023-12-10 11:18 UTC, JNechaevsky commented
Sure, all done.

2023-12-10 11:19 UTC, fabiangreffrath approved these changes
Perfect, thank you!

2023-12-10 11:20 UTC, merged

2023-12-10 11:38 UTC, JNechaevsky commented
My pleasure! Crispy definitely deserves this change for all games as well, and I remember for sure Heretic have some extra redundant palette flashes like [this one](https://github.com/fabiangreffrath/crispy-doom/blob/master/src/heretic/p_inter.c#L914). Gladly will do, but first I need to solve GammaTables issue for true color, it feels like TC needs one extra call for gamma table, but I'm at dead end there and can't understand why exactly such call is needed.

What's seriously bothering me is - I remember exactly we was discussing `ST_doPaletteStuff` earlier, and remember for sure you have suggested to use it in the end of `ST_Ticker` because of "calculations first, drawing second" logics. But why it wasn't committed into Crispy/Woof - no idea, it's like yet another black hole in my memory. Looks likes I'm getting too old. ☹️

2023-12-12 08:03 UTC, fabiangreffrath commented
> My pleasure! Crispy definitely deserves this change for all games as well, and I remember for sure Heretic have some extra redundant palette flashes like [this one](https://github.com/fabiangreffrath/crispy-doom/blob/master/src/heretic/p_inter.c#L914). Gladly will do, but first I need to solve GammaTables issue for true color, it feels like TC needs one extra call for gamma table, but I'm at dead end there and can't understand why exactly such call is needed.

I'll reply to this in the `gamma` pr over at Crispy.

> What's seriously bothering me is - I remember exactly we was discussing `ST_doPaletteStuff` earlier, and remember for sure you have suggested to use it in the end of `ST_Ticker` because of "calculations first, drawing second" logics. But why it wasn't committed into Crispy/Woof - no idea, it's like yet another black hole in my memory. Looks likes I'm getting too old. ☹️

Nope, we are just crowded with real-life stuff and have too many software projects to juggle. I always tend to forget stuff that I haven't written down "somewhere". In case of my software projects, that'd be the Github tracker. I wouldn't remember a single bug report from the DW forums or discord, no chance. :grin: And, yes, we are getting old. Maybe priorities have also shifted a bit. Remember, *it's just a game*!

2023-12-12 18:23 UTC, JNechaevsky commented
Oh, sometimes I have hilarious situations on day job like:
— Remember, few months ago we was talking about `insert some job stuff here`?
— Yes, I remember something like that _(while my real, honest answer should be like: "What? We? Was talking? When? About what? What do you want from me? ~~Who are you?~~")_.

But you right. You always right, that's why I'm always trust you, and always would like to ask for recommendation. I wish I could ask for some kind of personal reminder or TODOer, but no, in current context it would be disrespectful act of not good humor, and the last thing I want to make jokes about, even on friendly manner, is age. Our age, to be fair, just two more years, and now I'll reach that... evil number. 🙂

2023-12-13 08:19 UTC, fabiangreffrath commented
> But you right. You always right, that's why I'm always trust you, 

Thank you! I'll try my very best.

>  evil number.

I've crossed this barrier some years ago and in the end, it was just another birthday. The people surrounding you are growing older as well. The children are getting older. Few days ago my son told me I behave like a child trapped in an old man's body. Incredible that for him I'm old wheras for myself I am not. 😁