Fix wiggling on edges of floors/ceilings
fabiangreffrath/woof pull request #518
Opened 2022-04-15 05:29 UTC by facespkz

Ports Crispy's wiggle fix code to prevent distorted floors and ceilings.

2022-04-15 13:44 UTC, rfomin approved these changes
Thank you for this! Looks good to me, but it seems we'll have to wait a few days for @fabiangreffrath's review.

2022-04-25 06:33 UTC, fabiangreffrath commented
I remember I once had this in a very early branch but rejected it, because I found the port doesn't really need it (because of its limited resolution). What it really benefited from was the necessary upgrade of renderer variables to 32-bit integers, though, which has already been implemented independent if the actual wiggle fix.

2022-04-25 06:42 UTC, fabiangreffrath requested changes

2022-04-25 06:42 UTC, fabiangreffrath commented on Source/r_segs.c
> +// WiggleFix: add this code block near the top of r_segs.c
Could you move this down a bit, right before `R_RenderSegLoop()` so you could use the `HEIGHTBITS` and `HEIGHTUNIT` macros for initialization of the `heightbits` and `heightunit` variables?

2022-04-25 06:42 UTC, fabiangreffrath commented on Source/r_main.c
> +#if 0
Please remove this code, instead of commenting it out, but leave the comment in place.

2022-04-26 06:05 UTC, fabiangreffrath commented on Source/r_segs.c
> +
Excess blank line.

2022-04-26 06:44 UTC, facespkz commented on Source/r_segs.c
> +
oops

2022-04-26 11:58 UTC, merged